[theme]
primaryColor="#F63366"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"
base="light"

[global]
dataFrameSerialization = "legacy"

[server]
maxUploadSize = 10
runOnSave = true

[runner]
magicEnabled = false
fastReruns = false